### PR TITLE
Goals for Tabliss 2 [Request For Comment]

### PR DESCRIPTION
**Pull request by joelshepherd**
See pretty version of the planning document: [Tabliss 2 Planning Document](https://github.com/joelshepherd/tabliss/blob/rfc-2/docs/Tabliss_2.md)

I am creating this PR to open up my planning of Tabliss version 2 to anyone who wants to contribute.

So far I have added some of the most requested features that would require a design changes to "Feature Goals". And some of my personal thoughts about the technical implementation in "Technical Goals".

Some questions I am still working on:
- Should you be able to have more than 1 of a single widget?
- Should they share state or not?
- How to implement a flexible widget layout system?
  - Snapping grid system
  - Draggable absolute (%) positioning
  - Layout slots - similar to Apple Watch complications

### CODE REVIEW

**Comment by wa4-fearless-otter** [comment]
> Should you be able to have more than 1 of a single widget?

Sounds like a good idea.

> Should they share state or not?

I think this should be adjustable. For example, the suggestions of a seach widget shouldn't share the state with another search widget, but a calendar should share the state. This could be set by the user in the settings.

**Comment by wa4-fearless-otter** [comment]
Maybe rework the settings menu to a bigger (maybe fullscreen) menu. It would make it easier to add new settings and I think it would improve ux.

**Comment by joelshepherd** [comment]
Yeah I agree on the settings menu. I noticed this quite a bit when you start adding heaps of links. The tiny sidebar becomes unwieldy pretty quickly.

**Comment by wa4-fearless-otter** [comment]
#135 would also fit in here.

**Pull request merged**
