### PR TITLE
fix: Updated github-calendar package with upstream skylines fix

### LINKED ISSUE #515: Github Calendar Widget Shows Text
The widget shows the text linking to the 3d visualisation...

I'd imagine nobody wants that.

### PR DESCRIPTION
**Pull request by hughesjs**
Fixes #515 

Signed-off-by: James Hughes <james.hughes@codurance.com>

### CODE REVIEW

**Comment by gonzalrick** [comment]
Thanks for the fix @hughesjs

**Review by gonzalrick — APPROVED** [review]

**Comment by hughesjs** [comment]
Will this auto-update the Firefox package?

**Comment by gonzalrick** [comment]
We will need to release the new tabliss version and be approved by the web browser extension stores (chrome, firefox & edge). @joelshepherd can correct me here if Im wrong

**Comment by hughesjs** [comment]
Ahh that's a shame, I was hoping that there'd be some CD... Any ideas on roughly how long that normally takes?

**Pull request merged**
