### PR TITLE
Migrate settings over to boostrap, change cards to Drag and Drop and other tweeks to settings

### PR DESCRIPTION
**Pull request by trickypr**
## Done in this request
- [x] Add bootstrap using reactstrap
- [x] Optimize Bootstrap, including adding auto prefixer 
- [x] Settings can be moved using drag and drop
- [x] Better icon selector for quick links
- [x] Square location selector for widgets (This is horrible, tell me if you want it reverted)
- [x] Make the "Set as default page" button more visible (partially done) (#182, #81)

## Probably should be done in this request
- [x] Custom theme for bootstrap (Not including dark mode)
- [ ] Lazy loading reactstrap elements (Not necessary, can be done later)
- [x] Fix conflicts with master
- [ ] Refactor all the code written

## Needs to be done else were
- [ ] Change the number of columns that settings can use (#115)
- [ ] Collapse local image list / all photo settings (#136)
- [ ] Some kind of custom theming system (including dark mode) (#146)
- [ ] Max rows on lists (#167) & redesign lists

### CODE REVIEW

**Comment by trickypr** [comment]
Finally done! This pull request includes:
- Updating the settings to use bootstrap to standardize everything
- Drag and Drop to reorder widgets
- Square based widget position changer

## Screenshots
<details>
<summary>Bootstrap</summary>

Settings with bootstrap

Bootstrap provides consistent styling, integration with React and a consistent structure that makes it easy to theme.
</details>

<details>
<summary>Widget position changer</summary>

image
</details>

**Comment by joelshepherd** [comment]
Thanks for getting this in!

After some internal debating I decided to push out Tabliss 2 before I merge this in. That will give me extra time to polish the styling and improve the performance of bringing in a new library. Time I just didn't have this long weekend, at least if I still wanted to get Tabliss 2 launched!

I'll pick this back up on the weekend and get it merged in. Thank you for all your hard work here!

**Comment by trickypr** [comment]
No problem, thanks for all the amazing work you do!

**Comment by trickypr** [comment]
The more I have been thinking about it, the more I think that bootstrap and all the other ui libraries I have experimented with are hard to customize, large and slow to load or both. 
Bootstrap was the best of the bunch but is by no means the best. You can't customize it using CSS variables, making it hard to theme dynamically (like adding a dark mode). It isn't flexible enough to be used for the dashboard. It just adds extra bloat for not that much gain.
It would be much better to refactor the current ui system so it is easier to drop into new situations or write a custom one.

**Pull request closed without merging**
