### PR TITLE
Fixed issue with Giphy not loading images

### PR DESCRIPTION
**Pull request by OneComputerGuy**
Giphy changed the way the data in the object is sent. Modified the path to get the original image URL to the correct one in the new Object.

### CODE REVIEW

**Comment by OneComputerGuy** [comment]
@joelshepherd not sure if this can be merged "as is". It's just a line of code that changed. This fixes the issue reported since Nov 2021

**Comment by joelshepherd** [comment]
Just checked the docs, I couldn't find `images.original.url` in there? Undocumented field maybe?

**Comment by OneComputerGuy** [comment]
It might be, although it seems that what it changed was the way the object carries the information rather than the contents of it.

They seem to have compartmentalized the data in individual objects instead of having all the data in the main tree

**Comment by OneComputerGuy** [comment]
Their API explorer does show now the new Object tree though:

image

**Comment by noah-curran** [comment]
@joelshepherd It actually is documented.
If you look [here](https://developers.giphy.com/docs/api/endpoint#random) it says that the random endpoint returns a [GIF Object](https://developers.giphy.com/docs/api/schema/#gif-object) (not an Image Object that you linked).
You'll see that the GIF Object does document the inclusion of the `url` field.

**Comment by OneComputerGuy** [comment]
Oh I think what was Joel referring to. The Images Object itself doesn’t have documented the URL field in the docs, but the response does include that field. So yeah, it is undocumented.
image

**Comment by OneComputerGuy** [comment]
The code itself creates a blob out of that URL so, technically, it can use any stream, however, testing with the mp4 feed breaks somehow the functionality and doesn't load the GIF in the tab (doesn't show any error in the console either).

It does works with the original or the webp URL, so I kept the original to be safe (and to keep the original route Joel had)

**Comment by noah-curran** [comment]
Makes sense! Thanks for the info.

**Comment by joelshepherd** [comment]
I would support changing to the `webp` format if it works. I feel better about using a documented field, less likely it'll break on us again :joy:

**Comment by OneComputerGuy** [comment]
Yup, better safe than sorry 😅. I updated the source on the commit and it's ready for review

**Review by joelshepherd — APPROVED** [review]
Thanks again for fixing/testing this.

**Comment by w10000326** [comment]
It is still a solid black screen on Firefox, and I am still finding errors when inspecting the tab. 

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
    ke main.js:3392
    rn main.js:18754
    l main.js:18705
    l main.js:18720
    o main.js:18604


When examining this, it still looks like it's not able to grab anything from Giphy? I apologize if this is the incorrect place for this.

**Comment by OneComputerGuy** [comment]
@w10000326 I believe Joel merged the changes but hasn't pushed the new version with the changes to the Chrome store. I think he's finishing up a database rewrite to push all the changes at once.

**Pull request merged**
