### PR TITLE
Add "Literature Clock" widget

### PR DESCRIPTION
**Pull request by lbngoc**
Clock using time quotes from the literature, based on work and idea by
        [Jaap Meijers](http://www.eerlijkemedia.nl/) ([E-reader clock](https://www.instructables.com/id/Literary-Clock-Made-From-E-reader/)).

### CODE REVIEW

**Comment by joelshepherd** [comment]
Hey, this looks great! Is it ready to merge in (I see you made some changes recently)?

**Comment by lbngoc** [comment]
Yes.
Today I re-test with Firefox and faced some errors so that I changed some code to fix all them.
It's already working on my side, you can re-check it on your side.

**Comment by joelshepherd** [comment]
Okay awesome, I'll merge it in! If I run into any issues on my end, I'll fix them here.

Thanks for your contribution! I'll have this available in the next Tabliss release 😄

**Comment by lbngoc** [comment]
Great! 
Looking forward to get new Tabliss release ^_^

**Pull request merged**
