### PR TITLE
Updated npm dependencies

### PR DESCRIPTION
**Pull request by wa4-fearless-otter**
Depends on #101

### CODE REVIEW

**Comment by joelshepherd** [comment]
Hi, does people's previous setting carry over when upgrading from `redux-persist@4` to `redux-persist@5`?

**Comment by Wavum** [comment]
No, but there is an [experimental state migration](https://github.com/rt2zz/redux-persist/blob/master/docs/MigrationGuide-v5.md#experimental-v4-to-v5-state-migration) from v4 to v5, should I implement it?

**Comment by joelshepherd** [comment]
> warning: this method is completely untested
Fills me with great confidence!

I have planned on staging the storage mechanism soon. So I think I may push out a release with the current changes first, then merge the updates in after.

Thanks!

**Comment by joelshepherd** [comment]
Hey, I have rewritten the storage mechanism + migration to work with the new version of `redux-persist` (and fixed a few bugs in the process).

I was pulling in parts of your work as I was rewritting, but things have diverged so much I am not actually able to merge this PR in anymore 🤦‍♂

But thanks for your work here, most of it has made it into `master` now as part of the Tabliss 2 rewrite.

**Pull request closed without merging**
